#!/usr/bin/env python3
# -*- coding:utf-8 -*-

# Actuator modeling
# Trust generated by a propeller

# TODO: Add 1st order dynamic model
# TODO: Add angular position to compute induced mechanical noise


def thrust(cmd):

    # f = 10*cmd*cmd
    f = 12*cmd

    return f # [N]
