#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Polynomial Estimator GUI (Qt version using .ui file)
---------------------------------------------------
Loads its interface from ``polynomial.ui`` created with Qt Designer.
Requires:
    PyQt5   (pip3 install PyQt5)
    NumPy   (pip3 install numpy)
"""

import sys
import os
from typing import List

import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QHeaderView
from PyQt5.QtCore import Qt

class PolyEstimatorGUI(QtWidgets.QMainWindow):
    """Main window for the polynomial estimator."""

    def __init__(self):
        super().__init__()
        self._load_ui()

        # Public attributes the original API exposed
        self.C: List[float] | None = None  # type: ignore[invalid-annotation]
        self.coefs_computed: bool = False

        # Connect signals to slots
        self.btn_add.clicked.connect(self.add_point)
        self.btn_del.clicked.connect(self.del_points)
        self.btn_compute.clicked.connect(self.poly_identification)

    # ------------------------------------------------------------------
    # UI loading
    # ------------------------------------------------------------------
    def _load_ui(self) -> None:
        """Load the interface generated by Qt Designer."""
        script_dir = os.path.dirname(os.path.abspath(__file__))
        uic.loadUi(os.path.join(script_dir, "polynomial.ui"), self)



        # Try to set an icon if it lives in ./resources/
        icon_path = os.path.join(script_dir, "resources", "poly_est_icon.png")
        if os.path.exists(icon_path):
            self.setWindowIcon(QtGui.QIcon(icon_path))

        self.setWindowTitle("Polynomial estimation")

        # Give convenient attribute names (they already exist from ui object names)
        # tableWidget -> table, etc.
        self.table: QtWidgets.QTableWidget = self.tableWidget  # type: ignore[attr-defined]

        header = self.table.horizontalHeader()
        header.setSectionResizeMode(QHeaderView.Stretch)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def get_coefs(self):
        return self.C

    def has_coefs(self) -> bool:
        return self.coefs_computed

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _show_error(self, text: str) -> None:
        QtWidgets.QMessageBox.critical(self, "Error", text)

    # -- Add point -------------------------------------------------------
    def add_point(self) -> None:
        vx, vy = self.x_edit.text().strip(), self.y_edit.text().strip()
        if not (vx and vy):
            self._show_error("No number pair to add.")
            return
        try:
            float(vx)
            float(vy)
        except ValueError:
            self._show_error("Invalid entry. Must be a number.")
            return

        row = self.table.rowCount()
        self.table.insertRow(row)

        # self.table.setItem(row, 0, QtWidgets.QTableWidgetItem(vx))
        # self.table.setItem(row, 1, QtWidgets.QTableWidgetItem(vy))

        item_x = QtWidgets.QTableWidgetItem(vx)
        item_y = QtWidgets.QTableWidgetItem(vy)
        item_x.setTextAlignment(Qt.AlignCenter)
        item_y.setTextAlignment(Qt.AlignCenter)
        self.table.setItem(row, 0, item_x)
        self.table.setItem(row, 1, item_y)

        self.x_edit.clear()
        self.y_edit.clear()
        self.x_edit.setFocus()

    # -- Delete selected rows -------------------------------------------
    def del_points(self) -> None:
        selected = self.table.selectionModel().selectedRows()
        for idx in sorted((s.row() for s in selected), reverse=True):
            self.table.removeRow(idx)

    # -- Compute polynomial ---------------------------------------------
    def poly_identification(self) -> None:
        n_pts = self.table.rowCount()
        if n_pts < 3:
            self._show_error("Add at least 3 points.")
            return

        try:
            xv = np.array([float(self.table.item(r, 0).text()) for r in range(n_pts)])
            yv = np.array([float(self.table.item(r, 1).text()) for r in range(n_pts)])
        except Exception:
            self._show_error("Invalid numeric data in table.")
            return

        A = np.column_stack([np.ones_like(xv), xv, xv**2])
        try:
            self.C = np.linalg.inv(A.T @ A) @ A.T @ yv
            self.coefs_computed = True
            self._display_poly(self.C)
        except np.linalg.LinAlgError:
            self._show_error("Error computing coefficients. Check the input values.")

    # -- Display result --------------------------------------------------
    def _display_poly(self, c):
        terms = []
        for i, coeff in enumerate(c):
            r = round(coeff * 1000) / 1000
            sign = " + " if r >= 0 and i else (" - " if r < 0 else "")
            abs_val = abs(r)
            if i == 0:
                terms.append(f"{sign}{abs_val}")
            elif i == 1:
                terms.append(f"{sign}{abs_val}*u")
            else:
                terms.append(f"{sign}{abs_val}*u²")
        self.result_label.setText("p(u) = " + "".join(terms).lstrip())


# ----------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------

def main() -> None:
    app = QtWidgets.QApplication(sys.argv)
    gui = PolyEstimatorGUI()
    gui.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
